CREATE SCHEMA IF NOT EXISTS BCDBA;


CREATE SEQUENCE BCDBA.SEQ_MPMMERBASINFO
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE BCDBA.SEQ_MPMMERCDHDINFO
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE BCDBA.SEQ_MPMQRCRETCTNT
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE BCDBA.SEQ_MPMQRPAYPSTCLOG
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE BCDBA.SEQ_MPMMERCDHDCONNHST
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE BCDBA.SEQ_MPMMERCDHDINFOHST
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE BCDBA.SEQ_MPMMONIHST
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE BCDBA.SEQ_MPMQRSNDAPLC
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

